// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1mYvKOZzFXwtNPKOJddUVt4rzCmR68Q',
    appId: '1:16745918905:web:2aec7f9f0e7dfaa7f10668',
    messagingSenderId: '16745918905',
    projectId: 'faculty-appointment-sys',
    authDomain: 'faculty-appointment-sys.firebaseapp.com',
    storageBucket: 'faculty-appointment-sys.firebasestorage.app',
    measurementId: 'G-VTZXHHWNMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLYyE7_qdQTS3Y5YIrNDB_nvopfV95lw',
    appId: '1:16745918905:android:3d8de5d0e8b6edcef10668',
    messagingSenderId: '16745918905',
    projectId: 'faculty-appointment-sys',
    storageBucket: 'faculty-appointment-sys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9cazp9NLTVjg71JXyslu4rV7FbxTKKu8',
    appId: '1:16745918905:ios:c1be8fea28f1dca8f10668',
    messagingSenderId: '16745918905',
    projectId: 'faculty-appointment-sys',
    storageBucket: 'faculty-appointment-sys.firebasestorage.app',
    iosBundleId: 'com.isufst.facultyAppoinment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9cazp9NLTVjg71JXyslu4rV7FbxTKKu8',
    appId: '1:16745918905:ios:c1be8fea28f1dca8f10668',
    messagingSenderId: '16745918905',
    projectId: 'faculty-appointment-sys',
    storageBucket: 'faculty-appointment-sys.firebasestorage.app',
    iosBundleId: 'com.isufst.facultyAppoinment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW1mYvKOZzFXwtNPKOJddUVt4rzCmR68Q',
    appId: '1:16745918905:web:5f2bb6f45371c853f10668',
    messagingSenderId: '16745918905',
    projectId: 'faculty-appointment-sys',
    authDomain: 'faculty-appointment-sys.firebaseapp.com',
    storageBucket: 'faculty-appointment-sys.firebasestorage.app',
    measurementId: 'G-HZ29Z4QBWY',
  );
}
